# Generated by Django 2.2.4 on 2019-09-16 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primeira', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='quantidade',
            field=models.CharField(max_length=11),
        ),
    ]
